// Generated by CoffeeScript 1.3.3
(function() {

  window.Dot = {
    Models: {},
    Collections: {},
    Views: {},
    Routers: {},
    init: function() {
      $.fx.interval = 20;
      this.Routers.main = new Dot.Routers.Main();
      return Backbone.history.start();
    }
  };

  $(function() {
    return Dot.init();
  });

}).call(this);
