#!/bin/bash

coffee --output js/ --watch --compile coffee/*.coffee &
coffee --output js/models/ --watch --compile coffee/models/*.coffee &
coffee --output js/views/ --watch --compile coffee/views/*.coffee &
# coffee --output js/helpers/ --watch --compile coffee/helpers/*.coffee &
coffee --output js/routers/ --watch --compile coffee/routers/*.coffee &
coffee --output js/collections/ --watch --compile coffee/collections/*.coffee &
compass watch --sass-dir scss/ --css-dir css/ --output-style compressed --debug-info --trace &
./eco-compiler.js &
guard &
