// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Dot.Views.About = (function(_super) {

    __extends(About, _super);

    function About() {
      return About.__super__.constructor.apply(this, arguments);
    }

    About.prototype.template = JST['about'];

    About.prototype.className = 'about';

    About.prototype.events = {
      'click #about-back': 'back'
    };

    About.prototype.initialize = function(parent) {
      console.log(parent);
      this.parent = parent.parent;
      console.log('hai');
      console.log(this);
      return this.render();
    };

    About.prototype.render = function() {
      return $(this.el).html(this.template());
    };

    About.prototype.back = function(e) {
      e.preventDefault();
      return this.parent.$el.removeClass('flap_about');
    };

    return About;

  })(Backbone.View);

}).call(this);
