// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Dot.Collections.Colors = (function(_super) {

    __extends(Colors, _super);

    function Colors() {
      return Colors.__super__.constructor.apply(this, arguments);
    }

    Colors.prototype.model = Dot.Models.Color;

    Colors.prototype.url = '/colors.json';

    return Colors;

  })(Backbone.Collection);

}).call(this);
